baseurl = "https://dan-nixon.com"
title = "Dan Nixon"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[params]
    author = "Dan Nixon"
    info = "Scientific Software Engineer"
    description = "Dan Nixon's personal website"
    keywords = "developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

[[params.social]]
    name = "Matrix"
    icon = "fas fa-comment-dots fa-2x"
    weight = 1
    url = "https://matrix.to/#/@dannixon:matrix.org"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 2
    url = "mailto:dan@dan-nixon.com"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 3
    url = "https://github.com/dannixon/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/nixondan"

[[menu.main]]
    name = "About Me"
    weight = 1
    url = "/about/"

[markup.goldmark.renderer]
    unsafe = true
